(define rember 
	(lambda (x lat)
		(cond ((null? lat) (quote ()))
			  ((eq? x (car lat)) (cdr lat))
			  (else (cons (car lat) (rember x (cdr lat))))
		)
	)
)

(define firsts
	(lambda (lst)
		(cond ((null? lst) (quote ()))
			  (else (cons (car (car lst)) (firsts (cdr lst))))
		)
	)
)

(define insertR
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons old (cons new (cdr lat))))
							(else (cons (car lat) (insertR new old(cdr lat))))
					)
				)
		)
	)
)

(define insertL
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons new (cons old (cdr lat))))
							(else (cons (car lat) (insertL new old(cdr lat))))
					)
				)
		)
	)
)

(define subst
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons new (cdr lat)))
							(else (cons (car lat) (subst new old(cdr lat))))
					)
				)
		)
	)
)

(define subst2
	(lambda (new old1 old2 lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((or (eq? (car lat) old1) (eq? (car lat) old2)) (cons new (cdr lat)))
							(else (cons (car lat) (subst2 new old1 old2 (cdr lat))))
					)
				)
		)
	)
)

(define multirember 
	(lambda (x lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? x (car lat)) (multirember x (cdr lat))
						(cons (car lat) (multirember x (cdr lat)))
					)
				)	
		)
	)
)

(define multiInsertR
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons (car lat) (cons new (multiInsertR new old(cdr lat)))))
							(else (cons (car lat) (multiInsertR new old(cdr lat))))
					)
				)
		)
	)
)

(define multiInsertL
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons new(cons old (multiInsertR new old(cdr lat)))))
							(else (cons (car lat) (multiInsertL new old(cdr lat))))
					)
				)
		)
	)
)

(define multiSubst
	(lambda (new old lat)
		(cond ((null? lat) (quote ()))
			  (else (cond ((eq? (car lat) old) (cons new (multiSubst new old(cdr lat))))
							(else (cons (car lat) (multiSubst new old(cdr lat))))
					)
				)
		)
	)
)